server:
  port: 8189
  servlet:
    context-path: /market

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/products?currentSchema=products
    username: testadmin
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: utf-8
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
  jackson:
    serialization:
      indent_output: true

