server:
  port: 8189
  servlet:
    context-path: /market

spring:
  flyway:
    locations: classpath:/db/test_migration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2.mem.mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  resources:
    static-locations: file:src/main/resources/static/
  jackson:
    serialization:
      indent_output: true
jwt:
  secret: topsecretkey123rieubherotuh3498th398gh395g8h598gh4g8gidufghdifughi43gg4334t3h4gi34uhgi35uhgi35ughi45ugho98dhf98bhgD